"""
Core data models for the multiagent trading system
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
from datetime import datetime
from enum import Enum

class SignalStrength(Enum):
    VERY_WEAK = 0.2
    WEAK = 0.4
    NEUTRAL = 0.5
    STRONG = 0.7
    VERY_STRONG = 0.9

@dataclass
class MarketData:
    """Market data from a single exchange"""
    symbol: str
    exchange: str  # 'binance' or 'delta'
    timestamp: datetime
    price: float
    volume_24h: float
    volume_1h: float
    high_24h: float
    low_24h: float
    bid: float
    ask: float
    mark_price: Optional[float] = None  # For delta exchange
    funding_rate: Optional[float] = None  # For perpetuals
    open_interest: Optional[float] = None  # For perpetuals
    liquidation_volume: Optional[float] = None

@dataclass
class ComparativeMarketData:
    """Comparison of market data across exchanges"""
    symbol: str
    timestamp: datetime
    binance_data: MarketData
    delta_data: MarketData
    volume_premium: float  # Delta volume / Binance volume
    price_difference: float  # Percentage difference
    
@dataclass
class AgentSignal:
    """Signal generated by an agent"""
    agent_name: str
    symbol: str
    signal_type: str  # 'buy', 'sell', 'hold'
    strength: float  # 0.0 to 1.0
    confidence: float  # 0.0 to 1.0
    reasoning: str
    timestamp: datetime
    technical_indicators: Dict[str, float] = field(default_factory=dict)

@dataclass
class ConsensusResult:
    """Result from the consensus engine"""
    symbol: str
    final_signal: str  # 'buy', 'sell', 'hold'
    consensus_strength: float  # 0.0 to 1.0
    agent_signals: List[AgentSignal]
    voting_distribution: Dict[str, int]  # {'buy': 3, 'sell': 1, 'hold': 2}
    timestamp: datetime

@dataclass
class RiskAssessment:
    """Risk assessment for a potential trade"""
    symbol: str
    position_size: float
    entry_price: float
    stop_loss: float
    take_profit: float
    risk_reward_ratio: float
    max_portfolio_allocation: float
    volatility_score: float
    is_safe: bool
    reason: str

@dataclass
class TradeSignal:
    """Final executable trade signal"""
    symbol: str
    side: str  # 'buy' or 'sell'
    size: float
    entry_price: float
    stop_loss: float
    take_profit: float
    timeframe: str
    confidence_score: float
    risk_assessment: RiskAssessment
    timestamp: datetime
